import IISRusskaya_zernovachya_kompaniyaЦенаТовараEController from '../i-i-s-russkaya-zernovachya-kompaniya-цена-товара-e';

var IISRusskaya_zernovachya_kompaniyaЦенаТовараENewController = IISRusskaya_zernovachya_kompaniyaЦенаТовараEController;
export default IISRusskaya_zernovachya_kompaniyaЦенаТовараENewController;
