//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Russkaya_zernovachya_kompaniya
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Заказ.
    /// </summary>
    // *** Start programmer edit section *** (Заказ CustomAttributes)

    // *** End programmer edit section *** (Заказ CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗаказE", new string[] {
            "ДатаОтгрузки as \'Дата отгрузки\'",
            "ДатаОплаты as \'Дата оплаты\'",
            "Состояние as \'Состояние\'",
            "ЦенаТовара as \'Цена товара\'",
            "ЦенаТовара.Цена as \'Цена\'",
            "Сотрудник as \'Сотрудник\'",
            "Сотрудник.Emile as \'Emile\'"}, Hidden=new string[] {
            "ЦенаТовара.Цена",
            "Сотрудник.Emile"})]
    [MasterViewDefineAttribute("ЗаказE", "ЦенаТовара", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Цена")]
    [MasterViewDefineAttribute("ЗаказE", "Сотрудник", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Emile")]
    [View("ЗаказL", new string[] {
            "ДатаОтгрузки as \'Дата отгрузки\'",
            "ДатаОплаты as \'Дата оплаты\'",
            "Состояние as \'Состояние\'",
            "ЦенаТовара.Цена as \'Цена\'",
            "Сотрудник.Emile as \'Emile\'"})]
    public class Заказ : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДатаОтгрузки;
        
        private System.DateTime fДатаОплаты;
        
        private IIS.Russkaya_zernovachya_kompaniya.СостЗаказа fСостояние;
        
        private IIS.Russkaya_zernovachya_kompaniya.ЦенаТовара fЦенаТовара;
        
        private IIS.Russkaya_zernovachya_kompaniya.Сотрудник fСотрудник;
        
        // *** Start programmer edit section *** (Заказ CustomMembers)

        // *** End programmer edit section *** (Заказ CustomMembers)

        
        /// <summary>
        /// ДатаОплаты.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.ДатаОплаты CustomAttributes)

        // *** End programmer edit section *** (Заказ.ДатаОплаты CustomAttributes)
        public virtual System.DateTime ДатаОплаты
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.ДатаОплаты Get start)

                // *** End programmer edit section *** (Заказ.ДатаОплаты Get start)
                System.DateTime result = this.fДатаОплаты;
                // *** Start programmer edit section *** (Заказ.ДатаОплаты Get end)

                // *** End programmer edit section *** (Заказ.ДатаОплаты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.ДатаОплаты Set start)

                // *** End programmer edit section *** (Заказ.ДатаОплаты Set start)
                this.fДатаОплаты = value;
                // *** Start programmer edit section *** (Заказ.ДатаОплаты Set end)

                // *** End programmer edit section *** (Заказ.ДатаОплаты Set end)
            }
        }
        
        /// <summary>
        /// ДатаОтгрузки.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.ДатаОтгрузки CustomAttributes)

        // *** End programmer edit section *** (Заказ.ДатаОтгрузки CustomAttributes)
        public virtual System.DateTime ДатаОтгрузки
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.ДатаОтгрузки Get start)

                // *** End programmer edit section *** (Заказ.ДатаОтгрузки Get start)
                System.DateTime result = this.fДатаОтгрузки;
                // *** Start programmer edit section *** (Заказ.ДатаОтгрузки Get end)

                // *** End programmer edit section *** (Заказ.ДатаОтгрузки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.ДатаОтгрузки Set start)

                // *** End programmer edit section *** (Заказ.ДатаОтгрузки Set start)
                this.fДатаОтгрузки = value;
                // *** Start programmer edit section *** (Заказ.ДатаОтгрузки Set end)

                // *** End programmer edit section *** (Заказ.ДатаОтгрузки Set end)
            }
        }
        
        /// <summary>
        /// Состояние.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.Состояние CustomAttributes)

        // *** End programmer edit section *** (Заказ.Состояние CustomAttributes)
        public virtual IIS.Russkaya_zernovachya_kompaniya.СостЗаказа Состояние
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.Состояние Get start)

                // *** End programmer edit section *** (Заказ.Состояние Get start)
                IIS.Russkaya_zernovachya_kompaniya.СостЗаказа result = this.fСостояние;
                // *** Start programmer edit section *** (Заказ.Состояние Get end)

                // *** End programmer edit section *** (Заказ.Состояние Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.Состояние Set start)

                // *** End programmer edit section *** (Заказ.Состояние Set start)
                this.fСостояние = value;
                // *** Start programmer edit section *** (Заказ.Состояние Set end)

                // *** End programmer edit section *** (Заказ.Состояние Set end)
            }
        }
        
        /// <summary>
        /// Заказ.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.Сотрудник CustomAttributes)

        // *** End programmer edit section *** (Заказ.Сотрудник CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудник"})]
        [NotNull()]
        public virtual IIS.Russkaya_zernovachya_kompaniya.Сотрудник Сотрудник
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.Сотрудник Get start)

                // *** End programmer edit section *** (Заказ.Сотрудник Get start)
                IIS.Russkaya_zernovachya_kompaniya.Сотрудник result = this.fСотрудник;
                // *** Start programmer edit section *** (Заказ.Сотрудник Get end)

                // *** End programmer edit section *** (Заказ.Сотрудник Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.Сотрудник Set start)

                // *** End programmer edit section *** (Заказ.Сотрудник Set start)
                this.fСотрудник = value;
                // *** Start programmer edit section *** (Заказ.Сотрудник Set end)

                // *** End programmer edit section *** (Заказ.Сотрудник Set end)
            }
        }
        
        /// <summary>
        /// Заказ.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.ЦенаТовара CustomAttributes)

        // *** End programmer edit section *** (Заказ.ЦенаТовара CustomAttributes)
        [PropertyStorage(new string[] {
                "ЦенаТовара"})]
        [NotNull()]
        public virtual IIS.Russkaya_zernovachya_kompaniya.ЦенаТовара ЦенаТовара
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.ЦенаТовара Get start)

                // *** End programmer edit section *** (Заказ.ЦенаТовара Get start)
                IIS.Russkaya_zernovachya_kompaniya.ЦенаТовара result = this.fЦенаТовара;
                // *** Start programmer edit section *** (Заказ.ЦенаТовара Get end)

                // *** End programmer edit section *** (Заказ.ЦенаТовара Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.ЦенаТовара Set start)

                // *** End programmer edit section *** (Заказ.ЦенаТовара Set start)
                this.fЦенаТовара = value;
                // *** Start programmer edit section *** (Заказ.ЦенаТовара Set end)

                // *** End programmer edit section *** (Заказ.ЦенаТовара Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗаказE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаказE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаказE", typeof(IIS.Russkaya_zernovachya_kompaniya.Заказ));
                }
            }
            
            /// <summary>
            /// "ЗаказL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаказL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаказL", typeof(IIS.Russkaya_zernovachya_kompaniya.Заказ));
                }
            }
        }
    }
}
