//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Russkaya_zernovachya_kompaniya
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Категория товара.
    /// </summary>
    // *** Start programmer edit section *** (КатегорияТовара CustomAttributes)

    // *** End programmer edit section *** (КатегорияТовара CustomAttributes)
    [AutoAltered()]
    [Caption("Категория товара")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КатегорияТовараE", new string[] {
            "КодКатегории as \'Код категории\'"})]
    [View("КатегорияТовараL", new string[] {
            "КодКатегории as \'Код категории\'"})]
    public class КатегорияТовара : ICSSoft.STORMNET.DataObject
    {
        
        private int fКодКатегории;
        
        // *** Start programmer edit section *** (КатегорияТовара CustomMembers)

        // *** End programmer edit section *** (КатегорияТовара CustomMembers)

        
        /// <summary>
        /// КодКатегории.
        /// </summary>
        // *** Start programmer edit section *** (КатегорияТовара.КодКатегории CustomAttributes)

        // *** End programmer edit section *** (КатегорияТовара.КодКатегории CustomAttributes)
        public virtual int КодКатегории
        {
            get
            {
                // *** Start programmer edit section *** (КатегорияТовара.КодКатегории Get start)

                // *** End programmer edit section *** (КатегорияТовара.КодКатегории Get start)
                int result = this.fКодКатегории;
                // *** Start programmer edit section *** (КатегорияТовара.КодКатегории Get end)

                // *** End programmer edit section *** (КатегорияТовара.КодКатегории Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (КатегорияТовара.КодКатегории Set start)

                // *** End programmer edit section *** (КатегорияТовара.КодКатегории Set start)
                this.fКодКатегории = value;
                // *** Start programmer edit section *** (КатегорияТовара.КодКатегории Set end)

                // *** End programmer edit section *** (КатегорияТовара.КодКатегории Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КатегорияТовараE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КатегорияТовараE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КатегорияТовараE", typeof(IIS.Russkaya_zernovachya_kompaniya.КатегорияТовара));
                }
            }
            
            /// <summary>
            /// "КатегорияТовараL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КатегорияТовараL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КатегорияТовараL", typeof(IIS.Russkaya_zernovachya_kompaniya.КатегорияТовара));
                }
            }
        }
    }
}
