//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Russkaya_zernovachya_kompaniya
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Контрагент.
    /// </summary>
    // *** Start programmer edit section *** (Контрагент CustomAttributes)

    // *** End programmer edit section *** (Контрагент CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КонтрагентE", new string[] {
            "НаимОрг as \'Наим орг\'",
            "Фамилия as \'Фамилия\'",
            "Имя as \'Имя\'",
            "Отчество as \'Отчество\'",
            "Тип as \'Тип\'"})]
    [View("КонтрагентL", new string[] {
            "НаимОрг as \'Наим орг\'",
            "Фамилия as \'Фамилия\'",
            "Имя as \'Имя\'",
            "Отчество as \'Отчество\'",
            "Тип as \'Тип\'"})]
    public class Контрагент : ICSSoft.STORMNET.DataObject
    {
        
        private string fНаимОрг;
        
        private string fФамилия;
        
        private string fИмя;
        
        private string fОтчество;
        
        private IIS.Russkaya_zernovachya_kompaniya.ТипКонтрагента fТип;
        
        // *** Start programmer edit section *** (Контрагент CustomMembers)

        // *** End programmer edit section *** (Контрагент CustomMembers)

        
        /// <summary>
        /// Имя.
        /// </summary>
        // *** Start programmer edit section *** (Контрагент.Имя CustomAttributes)

        // *** End programmer edit section *** (Контрагент.Имя CustomAttributes)
        [StrLen(255)]
        public virtual string Имя
        {
            get
            {
                // *** Start programmer edit section *** (Контрагент.Имя Get start)

                // *** End programmer edit section *** (Контрагент.Имя Get start)
                string result = this.fИмя;
                // *** Start programmer edit section *** (Контрагент.Имя Get end)

                // *** End programmer edit section *** (Контрагент.Имя Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Контрагент.Имя Set start)

                // *** End programmer edit section *** (Контрагент.Имя Set start)
                this.fИмя = value;
                // *** Start programmer edit section *** (Контрагент.Имя Set end)

                // *** End programmer edit section *** (Контрагент.Имя Set end)
            }
        }
        
        /// <summary>
        /// НаимОрг.
        /// </summary>
        // *** Start programmer edit section *** (Контрагент.НаимОрг CustomAttributes)

        // *** End programmer edit section *** (Контрагент.НаимОрг CustomAttributes)
        [StrLen(255)]
        public virtual string НаимОрг
        {
            get
            {
                // *** Start programmer edit section *** (Контрагент.НаимОрг Get start)

                // *** End programmer edit section *** (Контрагент.НаимОрг Get start)
                string result = this.fНаимОрг;
                // *** Start programmer edit section *** (Контрагент.НаимОрг Get end)

                // *** End programmer edit section *** (Контрагент.НаимОрг Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Контрагент.НаимОрг Set start)

                // *** End programmer edit section *** (Контрагент.НаимОрг Set start)
                this.fНаимОрг = value;
                // *** Start programmer edit section *** (Контрагент.НаимОрг Set end)

                // *** End programmer edit section *** (Контрагент.НаимОрг Set end)
            }
        }
        
        /// <summary>
        /// Отчество.
        /// </summary>
        // *** Start programmer edit section *** (Контрагент.Отчество CustomAttributes)

        // *** End programmer edit section *** (Контрагент.Отчество CustomAttributes)
        [StrLen(255)]
        public virtual string Отчество
        {
            get
            {
                // *** Start programmer edit section *** (Контрагент.Отчество Get start)

                // *** End programmer edit section *** (Контрагент.Отчество Get start)
                string result = this.fОтчество;
                // *** Start programmer edit section *** (Контрагент.Отчество Get end)

                // *** End programmer edit section *** (Контрагент.Отчество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Контрагент.Отчество Set start)

                // *** End programmer edit section *** (Контрагент.Отчество Set start)
                this.fОтчество = value;
                // *** Start programmer edit section *** (Контрагент.Отчество Set end)

                // *** End programmer edit section *** (Контрагент.Отчество Set end)
            }
        }
        
        /// <summary>
        /// Тип.
        /// </summary>
        // *** Start programmer edit section *** (Контрагент.Тип CustomAttributes)

        // *** End programmer edit section *** (Контрагент.Тип CustomAttributes)
        public virtual IIS.Russkaya_zernovachya_kompaniya.ТипКонтрагента Тип
        {
            get
            {
                // *** Start programmer edit section *** (Контрагент.Тип Get start)

                // *** End programmer edit section *** (Контрагент.Тип Get start)
                IIS.Russkaya_zernovachya_kompaniya.ТипКонтрагента result = this.fТип;
                // *** Start programmer edit section *** (Контрагент.Тип Get end)

                // *** End programmer edit section *** (Контрагент.Тип Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Контрагент.Тип Set start)

                // *** End programmer edit section *** (Контрагент.Тип Set start)
                this.fТип = value;
                // *** Start programmer edit section *** (Контрагент.Тип Set end)

                // *** End programmer edit section *** (Контрагент.Тип Set end)
            }
        }
        
        /// <summary>
        /// Фамилия.
        /// </summary>
        // *** Start programmer edit section *** (Контрагент.Фамилия CustomAttributes)

        // *** End programmer edit section *** (Контрагент.Фамилия CustomAttributes)
        [StrLen(255)]
        public virtual string Фамилия
        {
            get
            {
                // *** Start programmer edit section *** (Контрагент.Фамилия Get start)

                // *** End programmer edit section *** (Контрагент.Фамилия Get start)
                string result = this.fФамилия;
                // *** Start programmer edit section *** (Контрагент.Фамилия Get end)

                // *** End programmer edit section *** (Контрагент.Фамилия Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Контрагент.Фамилия Set start)

                // *** End programmer edit section *** (Контрагент.Фамилия Set start)
                this.fФамилия = value;
                // *** Start programmer edit section *** (Контрагент.Фамилия Set end)

                // *** End programmer edit section *** (Контрагент.Фамилия Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КонтрагентE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КонтрагентE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КонтрагентE", typeof(IIS.Russkaya_zernovachya_kompaniya.Контрагент));
                }
            }
            
            /// <summary>
            /// "КонтрагентL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КонтрагентL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КонтрагентL", typeof(IIS.Russkaya_zernovachya_kompaniya.Контрагент));
                }
            }
        }
    }
}
