//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Russkaya_zernovachya_kompaniya
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Накладная.
    /// </summary>
    // *** Start programmer edit section *** (Накладная CustomAttributes)

    // *** End programmer edit section *** (Накладная CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("НакладнаяE", new string[] {
            "ВремяОтгрузки as \'Время отгрузки\'",
            "Примечание as \'Примечание\'",
            "Сумма as \'Сумма\'",
            "Тип as \'Тип\'",
            "СостНакладной as \'Сост накладной\'"})]
    [View("НакладнаяL", new string[] {
            "ВремяОтгрузки as \'Время отгрузки\'",
            "Примечание as \'Примечание\'",
            "Сумма as \'Сумма\'",
            "Тип as \'Тип\'",
            "СостНакладной as \'Сост накладной\'"})]
    public class Накладная : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fВремяОтгрузки;
        
        private string fПримечание;
        
        private double fСумма;
        
        private IIS.Russkaya_zernovachya_kompaniya.ТипНакладной fТип;
        
        private IIS.Russkaya_zernovachya_kompaniya.СостНакладной fСостНакладной;
        
        // *** Start programmer edit section *** (Накладная CustomMembers)

        // *** End programmer edit section *** (Накладная CustomMembers)

        
        /// <summary>
        /// ВремяОтгрузки.
        /// </summary>
        // *** Start programmer edit section *** (Накладная.ВремяОтгрузки CustomAttributes)

        // *** End programmer edit section *** (Накладная.ВремяОтгрузки CustomAttributes)
        public virtual System.DateTime ВремяОтгрузки
        {
            get
            {
                // *** Start programmer edit section *** (Накладная.ВремяОтгрузки Get start)

                // *** End programmer edit section *** (Накладная.ВремяОтгрузки Get start)
                System.DateTime result = this.fВремяОтгрузки;
                // *** Start programmer edit section *** (Накладная.ВремяОтгрузки Get end)

                // *** End programmer edit section *** (Накладная.ВремяОтгрузки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Накладная.ВремяОтгрузки Set start)

                // *** End programmer edit section *** (Накладная.ВремяОтгрузки Set start)
                this.fВремяОтгрузки = value;
                // *** Start programmer edit section *** (Накладная.ВремяОтгрузки Set end)

                // *** End programmer edit section *** (Накладная.ВремяОтгрузки Set end)
            }
        }
        
        /// <summary>
        /// Примечание.
        /// </summary>
        // *** Start programmer edit section *** (Накладная.Примечание CustomAttributes)

        // *** End programmer edit section *** (Накладная.Примечание CustomAttributes)
        [StrLen(255)]
        public virtual string Примечание
        {
            get
            {
                // *** Start programmer edit section *** (Накладная.Примечание Get start)

                // *** End programmer edit section *** (Накладная.Примечание Get start)
                string result = this.fПримечание;
                // *** Start programmer edit section *** (Накладная.Примечание Get end)

                // *** End programmer edit section *** (Накладная.Примечание Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Накладная.Примечание Set start)

                // *** End programmer edit section *** (Накладная.Примечание Set start)
                this.fПримечание = value;
                // *** Start programmer edit section *** (Накладная.Примечание Set end)

                // *** End programmer edit section *** (Накладная.Примечание Set end)
            }
        }
        
        /// <summary>
        /// СостНакладной.
        /// </summary>
        // *** Start programmer edit section *** (Накладная.СостНакладной CustomAttributes)

        // *** End programmer edit section *** (Накладная.СостНакладной CustomAttributes)
        public virtual IIS.Russkaya_zernovachya_kompaniya.СостНакладной СостНакладной
        {
            get
            {
                // *** Start programmer edit section *** (Накладная.СостНакладной Get start)

                // *** End programmer edit section *** (Накладная.СостНакладной Get start)
                IIS.Russkaya_zernovachya_kompaniya.СостНакладной result = this.fСостНакладной;
                // *** Start programmer edit section *** (Накладная.СостНакладной Get end)

                // *** End programmer edit section *** (Накладная.СостНакладной Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Накладная.СостНакладной Set start)

                // *** End programmer edit section *** (Накладная.СостНакладной Set start)
                this.fСостНакладной = value;
                // *** Start programmer edit section *** (Накладная.СостНакладной Set end)

                // *** End programmer edit section *** (Накладная.СостНакладной Set end)
            }
        }
        
        /// <summary>
        /// Сумма.
        /// </summary>
        // *** Start programmer edit section *** (Накладная.Сумма CustomAttributes)

        // *** End programmer edit section *** (Накладная.Сумма CustomAttributes)
        public virtual double Сумма
        {
            get
            {
                // *** Start programmer edit section *** (Накладная.Сумма Get start)

                // *** End programmer edit section *** (Накладная.Сумма Get start)
                double result = this.fСумма;
                // *** Start programmer edit section *** (Накладная.Сумма Get end)

                // *** End programmer edit section *** (Накладная.Сумма Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Накладная.Сумма Set start)

                // *** End programmer edit section *** (Накладная.Сумма Set start)
                this.fСумма = value;
                // *** Start programmer edit section *** (Накладная.Сумма Set end)

                // *** End programmer edit section *** (Накладная.Сумма Set end)
            }
        }
        
        /// <summary>
        /// Тип.
        /// </summary>
        // *** Start programmer edit section *** (Накладная.Тип CustomAttributes)

        // *** End programmer edit section *** (Накладная.Тип CustomAttributes)
        public virtual IIS.Russkaya_zernovachya_kompaniya.ТипНакладной Тип
        {
            get
            {
                // *** Start programmer edit section *** (Накладная.Тип Get start)

                // *** End programmer edit section *** (Накладная.Тип Get start)
                IIS.Russkaya_zernovachya_kompaniya.ТипНакладной result = this.fТип;
                // *** Start programmer edit section *** (Накладная.Тип Get end)

                // *** End programmer edit section *** (Накладная.Тип Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Накладная.Тип Set start)

                // *** End programmer edit section *** (Накладная.Тип Set start)
                this.fТип = value;
                // *** Start programmer edit section *** (Накладная.Тип Set end)

                // *** End programmer edit section *** (Накладная.Тип Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "НакладнаяE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View НакладнаяE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("НакладнаяE", typeof(IIS.Russkaya_zernovachya_kompaniya.Накладная));
                }
            }
            
            /// <summary>
            /// "НакладнаяL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View НакладнаяL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("НакладнаяL", typeof(IIS.Russkaya_zernovachya_kompaniya.Накладная));
                }
            }
        }
    }
}
