//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Russkaya_zernovachya_kompaniya
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Сост заказа.
    /// </summary>
    // *** Start programmer edit section *** (СостЗаказа CustomAttributes)

    // *** End programmer edit section *** (СостЗаказа CustomAttributes)
    public enum СостЗаказа
    {
        
        // *** Start programmer edit section *** (СостЗаказа.Новый CustomAttributes)

        // *** End programmer edit section *** (СостЗаказа.Новый CustomAttributes)
        Новый,
        
        // *** Start programmer edit section *** (СостЗаказа.Отмененный CustomAttributes)

        // *** End programmer edit section *** (СостЗаказа.Отмененный CustomAttributes)
        Отмененный,
    }
}
