//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Russkaya_zernovachya_kompaniya
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Сост накладной.
    /// </summary>
    // *** Start programmer edit section *** (СостНакладной CustomAttributes)

    // *** End programmer edit section *** (СостНакладной CustomAttributes)
    public enum СостНакладной
    {
        
        // *** Start programmer edit section *** (СостНакладной.Новая CustomAttributes)

        // *** End programmer edit section *** (СостНакладной.Новая CustomAttributes)
        Новая,
        
        // *** Start programmer edit section *** (СостНакладной.Выписанная CustomAttributes)

        // *** End programmer edit section *** (СостНакладной.Выписанная CustomAttributes)
        Выписанная,
    }
}
