//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Russkaya_zernovachya_kompaniya
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Сотрудник.
    /// </summary>
    // *** Start programmer edit section *** (Сотрудник CustomAttributes)

    // *** End programmer edit section *** (Сотрудник CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СотрудникE", new string[] {
            "Emile as \'Emile\'",
            "Фамилия as \'Фамилия\'",
            "Имя as \'Имя\'",
            "Отчество as \'Отчество\'",
            "Телефон as \'Телефон\'",
            "ТабелНомер as \'Табел номер\'",
            "Накладная as \'Накладная\'",
            "Накладная.Примечание as \'Примечание\'"}, Hidden=new string[] {
            "Накладная.Примечание"})]
    [MasterViewDefineAttribute("СотрудникE", "Накладная", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Примечание")]
    [View("СотрудникL", new string[] {
            "Emile as \'Emile\'",
            "Фамилия as \'Фамилия\'",
            "Имя as \'Имя\'",
            "Отчество as \'Отчество\'",
            "Телефон as \'Телефон\'",
            "ТабелНомер as \'Табел номер\'",
            "Накладная.Примечание as \'Примечание\'"})]
    public class Сотрудник : ICSSoft.STORMNET.DataObject
    {
        
        private string fEmile;
        
        private string fФамилия;
        
        private string fИмя;
        
        private string fОтчество;
        
        private string fТелефон;
        
        private int fТабелНомер;
        
        private IIS.Russkaya_zernovachya_kompaniya.Накладная fНакладная;
        
        // *** Start programmer edit section *** (Сотрудник CustomMembers)

        // *** End programmer edit section *** (Сотрудник CustomMembers)

        
        /// <summary>
        /// Emile.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудник.Emile CustomAttributes)

        // *** End programmer edit section *** (Сотрудник.Emile CustomAttributes)
        [StrLen(255)]
        public virtual string Emile
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудник.Emile Get start)

                // *** End programmer edit section *** (Сотрудник.Emile Get start)
                string result = this.fEmile;
                // *** Start programmer edit section *** (Сотрудник.Emile Get end)

                // *** End programmer edit section *** (Сотрудник.Emile Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудник.Emile Set start)

                // *** End programmer edit section *** (Сотрудник.Emile Set start)
                this.fEmile = value;
                // *** Start programmer edit section *** (Сотрудник.Emile Set end)

                // *** End programmer edit section *** (Сотрудник.Emile Set end)
            }
        }
        
        /// <summary>
        /// Имя.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудник.Имя CustomAttributes)

        // *** End programmer edit section *** (Сотрудник.Имя CustomAttributes)
        [StrLen(255)]
        public virtual string Имя
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудник.Имя Get start)

                // *** End programmer edit section *** (Сотрудник.Имя Get start)
                string result = this.fИмя;
                // *** Start programmer edit section *** (Сотрудник.Имя Get end)

                // *** End programmer edit section *** (Сотрудник.Имя Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудник.Имя Set start)

                // *** End programmer edit section *** (Сотрудник.Имя Set start)
                this.fИмя = value;
                // *** Start programmer edit section *** (Сотрудник.Имя Set end)

                // *** End programmer edit section *** (Сотрудник.Имя Set end)
            }
        }
        
        /// <summary>
        /// Отчество.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудник.Отчество CustomAttributes)

        // *** End programmer edit section *** (Сотрудник.Отчество CustomAttributes)
        [StrLen(255)]
        public virtual string Отчество
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудник.Отчество Get start)

                // *** End programmer edit section *** (Сотрудник.Отчество Get start)
                string result = this.fОтчество;
                // *** Start programmer edit section *** (Сотрудник.Отчество Get end)

                // *** End programmer edit section *** (Сотрудник.Отчество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудник.Отчество Set start)

                // *** End programmer edit section *** (Сотрудник.Отчество Set start)
                this.fОтчество = value;
                // *** Start programmer edit section *** (Сотрудник.Отчество Set end)

                // *** End programmer edit section *** (Сотрудник.Отчество Set end)
            }
        }
        
        /// <summary>
        /// ТабелНомер.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудник.ТабелНомер CustomAttributes)

        // *** End programmer edit section *** (Сотрудник.ТабелНомер CustomAttributes)
        public virtual int ТабелНомер
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудник.ТабелНомер Get start)

                // *** End programmer edit section *** (Сотрудник.ТабелНомер Get start)
                int result = this.fТабелНомер;
                // *** Start programmer edit section *** (Сотрудник.ТабелНомер Get end)

                // *** End programmer edit section *** (Сотрудник.ТабелНомер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудник.ТабелНомер Set start)

                // *** End programmer edit section *** (Сотрудник.ТабелНомер Set start)
                this.fТабелНомер = value;
                // *** Start programmer edit section *** (Сотрудник.ТабелНомер Set end)

                // *** End programmer edit section *** (Сотрудник.ТабелНомер Set end)
            }
        }
        
        /// <summary>
        /// Телефон.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудник.Телефон CustomAttributes)

        // *** End programmer edit section *** (Сотрудник.Телефон CustomAttributes)
        [StrLen(255)]
        public virtual string Телефон
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудник.Телефон Get start)

                // *** End programmer edit section *** (Сотрудник.Телефон Get start)
                string result = this.fТелефон;
                // *** Start programmer edit section *** (Сотрудник.Телефон Get end)

                // *** End programmer edit section *** (Сотрудник.Телефон Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудник.Телефон Set start)

                // *** End programmer edit section *** (Сотрудник.Телефон Set start)
                this.fТелефон = value;
                // *** Start programmer edit section *** (Сотрудник.Телефон Set end)

                // *** End programmer edit section *** (Сотрудник.Телефон Set end)
            }
        }
        
        /// <summary>
        /// Фамилия.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудник.Фамилия CustomAttributes)

        // *** End programmer edit section *** (Сотрудник.Фамилия CustomAttributes)
        [StrLen(255)]
        public virtual string Фамилия
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудник.Фамилия Get start)

                // *** End programmer edit section *** (Сотрудник.Фамилия Get start)
                string result = this.fФамилия;
                // *** Start programmer edit section *** (Сотрудник.Фамилия Get end)

                // *** End programmer edit section *** (Сотрудник.Фамилия Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудник.Фамилия Set start)

                // *** End programmer edit section *** (Сотрудник.Фамилия Set start)
                this.fФамилия = value;
                // *** Start programmer edit section *** (Сотрудник.Фамилия Set end)

                // *** End programmer edit section *** (Сотрудник.Фамилия Set end)
            }
        }
        
        /// <summary>
        /// Сотрудник.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудник.Накладная CustomAttributes)

        // *** End programmer edit section *** (Сотрудник.Накладная CustomAttributes)
        [PropertyStorage(new string[] {
                "Накладная"})]
        [NotNull()]
        public virtual IIS.Russkaya_zernovachya_kompaniya.Накладная Накладная
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудник.Накладная Get start)

                // *** End programmer edit section *** (Сотрудник.Накладная Get start)
                IIS.Russkaya_zernovachya_kompaniya.Накладная result = this.fНакладная;
                // *** Start programmer edit section *** (Сотрудник.Накладная Get end)

                // *** End programmer edit section *** (Сотрудник.Накладная Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудник.Накладная Set start)

                // *** End programmer edit section *** (Сотрудник.Накладная Set start)
                this.fНакладная = value;
                // *** Start programmer edit section *** (Сотрудник.Накладная Set end)

                // *** End programmer edit section *** (Сотрудник.Накладная Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СотрудникE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СотрудникE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СотрудникE", typeof(IIS.Russkaya_zernovachya_kompaniya.Сотрудник));
                }
            }
            
            /// <summary>
            /// "СотрудникL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СотрудникL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СотрудникL", typeof(IIS.Russkaya_zernovachya_kompaniya.Сотрудник));
                }
            }
        }
    }
}
