//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Russkaya_zernovachya_kompaniya
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Строка заказа.
    /// </summary>
    // *** Start programmer edit section *** (СтрокаЗаказа CustomAttributes)

    // *** End programmer edit section *** (СтрокаЗаказа CustomAttributes)
    [AutoAltered()]
    [Caption("Строка заказа")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СтрокаЗаказаE", new string[] {
            "ЦенаСНалог as \'Цена с налог\'",
            "Количество as \'Количество\'",
            "Сумма as \'Сумма\'"})]
    [View("СтрокаЗаказаL", new string[] {
            "ЦенаСНалог as \'Цена с налог\'",
            "Количество as \'Количество\'",
            "Сумма as \'Сумма\'"})]
    public class СтрокаЗаказа : ICSSoft.STORMNET.DataObject
    {
        
        private double fЦенаСНалог;
        
        private int fКоличество;
        
        private double fСумма;
        
        // *** Start programmer edit section *** (СтрокаЗаказа CustomMembers)

        // *** End programmer edit section *** (СтрокаЗаказа CustomMembers)

        
        /// <summary>
        /// Количество.
        /// </summary>
        // *** Start programmer edit section *** (СтрокаЗаказа.Количество CustomAttributes)

        // *** End programmer edit section *** (СтрокаЗаказа.Количество CustomAttributes)
        public virtual int Количество
        {
            get
            {
                // *** Start programmer edit section *** (СтрокаЗаказа.Количество Get start)

                // *** End programmer edit section *** (СтрокаЗаказа.Количество Get start)
                int result = this.fКоличество;
                // *** Start programmer edit section *** (СтрокаЗаказа.Количество Get end)

                // *** End programmer edit section *** (СтрокаЗаказа.Количество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СтрокаЗаказа.Количество Set start)

                // *** End programmer edit section *** (СтрокаЗаказа.Количество Set start)
                this.fКоличество = value;
                // *** Start programmer edit section *** (СтрокаЗаказа.Количество Set end)

                // *** End programmer edit section *** (СтрокаЗаказа.Количество Set end)
            }
        }
        
        /// <summary>
        /// Сумма.
        /// </summary>
        // *** Start programmer edit section *** (СтрокаЗаказа.Сумма CustomAttributes)

        // *** End programmer edit section *** (СтрокаЗаказа.Сумма CustomAttributes)
        public virtual double Сумма
        {
            get
            {
                // *** Start programmer edit section *** (СтрокаЗаказа.Сумма Get start)

                // *** End programmer edit section *** (СтрокаЗаказа.Сумма Get start)
                double result = this.fСумма;
                // *** Start programmer edit section *** (СтрокаЗаказа.Сумма Get end)

                // *** End programmer edit section *** (СтрокаЗаказа.Сумма Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СтрокаЗаказа.Сумма Set start)

                // *** End programmer edit section *** (СтрокаЗаказа.Сумма Set start)
                this.fСумма = value;
                // *** Start programmer edit section *** (СтрокаЗаказа.Сумма Set end)

                // *** End programmer edit section *** (СтрокаЗаказа.Сумма Set end)
            }
        }
        
        /// <summary>
        /// ЦенаСНалог.
        /// </summary>
        // *** Start programmer edit section *** (СтрокаЗаказа.ЦенаСНалог CustomAttributes)

        // *** End programmer edit section *** (СтрокаЗаказа.ЦенаСНалог CustomAttributes)
        public virtual double ЦенаСНалог
        {
            get
            {
                // *** Start programmer edit section *** (СтрокаЗаказа.ЦенаСНалог Get start)

                // *** End programmer edit section *** (СтрокаЗаказа.ЦенаСНалог Get start)
                double result = this.fЦенаСНалог;
                // *** Start programmer edit section *** (СтрокаЗаказа.ЦенаСНалог Get end)

                // *** End programmer edit section *** (СтрокаЗаказа.ЦенаСНалог Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СтрокаЗаказа.ЦенаСНалог Set start)

                // *** End programmer edit section *** (СтрокаЗаказа.ЦенаСНалог Set start)
                this.fЦенаСНалог = value;
                // *** Start programmer edit section *** (СтрокаЗаказа.ЦенаСНалог Set end)

                // *** End programmer edit section *** (СтрокаЗаказа.ЦенаСНалог Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СтрокаЗаказаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СтрокаЗаказаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СтрокаЗаказаE", typeof(IIS.Russkaya_zernovachya_kompaniya.СтрокаЗаказа));
                }
            }
            
            /// <summary>
            /// "СтрокаЗаказаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СтрокаЗаказаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СтрокаЗаказаL", typeof(IIS.Russkaya_zernovachya_kompaniya.СтрокаЗаказа));
                }
            }
        }
    }
}
