//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Russkaya_zernovachya_kompaniya
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Счет фактура.
    /// </summary>
    // *** Start programmer edit section *** (СчетФактура CustomAttributes)

    // *** End programmer edit section *** (СчетФактура CustomAttributes)
    [AutoAltered()]
    [Caption("Счет фактура")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СчетФактураE", new string[] {
            "ДатаЗаполн as \'Дата заполн\'",
            "Номер as \'Номер\'",
            "Контрагент as \'Контрагент\'",
            "Контрагент.НаимОрг as \'Наим орг\'",
            "Заказ as \'Заказ\'",
            "Заказ.ДатаОтгрузки as \'Дата отгрузки\'",
            "Склад as \'Склад\'",
            "Склад.Адрес as \'Адрес\'",
            "Сотрудник as \'Сотрудник\'",
            "Сотрудник.Emile as \'Emile\'"}, Hidden=new string[] {
            "Контрагент.НаимОрг",
            "Заказ.ДатаОтгрузки",
            "Склад.Адрес",
            "Сотрудник.Emile"})]
    [MasterViewDefineAttribute("СчетФактураE", "Контрагент", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "НаимОрг")]
    [MasterViewDefineAttribute("СчетФактураE", "Заказ", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ДатаОтгрузки")]
    [MasterViewDefineAttribute("СчетФактураE", "Склад", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Адрес")]
    [MasterViewDefineAttribute("СчетФактураE", "Сотрудник", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Emile")]
    [View("СчетФактураL", new string[] {
            "ДатаЗаполн as \'Дата заполн\'",
            "Номер as \'Номер\'",
            "Контрагент.НаимОрг as \'Наим орг\'",
            "Заказ.ДатаОтгрузки as \'Дата отгрузки\'",
            "Склад.Адрес as \'Адрес\'",
            "Сотрудник.Emile as \'Emile\'"})]
    public class СчетФактура : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДатаЗаполн;
        
        private int fНомер;
        
        private IIS.Russkaya_zernovachya_kompaniya.Контрагент fКонтрагент;
        
        private IIS.Russkaya_zernovachya_kompaniya.Заказ fЗаказ;
        
        private IIS.Russkaya_zernovachya_kompaniya.Склад fСклад;
        
        private IIS.Russkaya_zernovachya_kompaniya.Сотрудник fСотрудник;
        
        // *** Start programmer edit section *** (СчетФактура CustomMembers)

        // *** End programmer edit section *** (СчетФактура CustomMembers)

        
        /// <summary>
        /// ДатаЗаполн.
        /// </summary>
        // *** Start programmer edit section *** (СчетФактура.ДатаЗаполн CustomAttributes)

        // *** End programmer edit section *** (СчетФактура.ДатаЗаполн CustomAttributes)
        public virtual System.DateTime ДатаЗаполн
        {
            get
            {
                // *** Start programmer edit section *** (СчетФактура.ДатаЗаполн Get start)

                // *** End programmer edit section *** (СчетФактура.ДатаЗаполн Get start)
                System.DateTime result = this.fДатаЗаполн;
                // *** Start programmer edit section *** (СчетФактура.ДатаЗаполн Get end)

                // *** End programmer edit section *** (СчетФактура.ДатаЗаполн Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СчетФактура.ДатаЗаполн Set start)

                // *** End programmer edit section *** (СчетФактура.ДатаЗаполн Set start)
                this.fДатаЗаполн = value;
                // *** Start programmer edit section *** (СчетФактура.ДатаЗаполн Set end)

                // *** End programmer edit section *** (СчетФактура.ДатаЗаполн Set end)
            }
        }
        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (СчетФактура.Номер CustomAttributes)

        // *** End programmer edit section *** (СчетФактура.Номер CustomAttributes)
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (СчетФактура.Номер Get start)

                // *** End programmer edit section *** (СчетФактура.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (СчетФактура.Номер Get end)

                // *** End programmer edit section *** (СчетФактура.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СчетФактура.Номер Set start)

                // *** End programmer edit section *** (СчетФактура.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (СчетФактура.Номер Set end)

                // *** End programmer edit section *** (СчетФактура.Номер Set end)
            }
        }
        
        /// <summary>
        /// Счет фактура.
        /// </summary>
        // *** Start programmer edit section *** (СчетФактура.Заказ CustomAttributes)

        // *** End programmer edit section *** (СчетФактура.Заказ CustomAttributes)
        [PropertyStorage(new string[] {
                "Заказ"})]
        [NotNull()]
        public virtual IIS.Russkaya_zernovachya_kompaniya.Заказ Заказ
        {
            get
            {
                // *** Start programmer edit section *** (СчетФактура.Заказ Get start)

                // *** End programmer edit section *** (СчетФактура.Заказ Get start)
                IIS.Russkaya_zernovachya_kompaniya.Заказ result = this.fЗаказ;
                // *** Start programmer edit section *** (СчетФактура.Заказ Get end)

                // *** End programmer edit section *** (СчетФактура.Заказ Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СчетФактура.Заказ Set start)

                // *** End programmer edit section *** (СчетФактура.Заказ Set start)
                this.fЗаказ = value;
                // *** Start programmer edit section *** (СчетФактура.Заказ Set end)

                // *** End programmer edit section *** (СчетФактура.Заказ Set end)
            }
        }
        
        /// <summary>
        /// Счет фактура.
        /// </summary>
        // *** Start programmer edit section *** (СчетФактура.Контрагент CustomAttributes)

        // *** End programmer edit section *** (СчетФактура.Контрагент CustomAttributes)
        [PropertyStorage(new string[] {
                "Контрагент"})]
        [NotNull()]
        public virtual IIS.Russkaya_zernovachya_kompaniya.Контрагент Контрагент
        {
            get
            {
                // *** Start programmer edit section *** (СчетФактура.Контрагент Get start)

                // *** End programmer edit section *** (СчетФактура.Контрагент Get start)
                IIS.Russkaya_zernovachya_kompaniya.Контрагент result = this.fКонтрагент;
                // *** Start programmer edit section *** (СчетФактура.Контрагент Get end)

                // *** End programmer edit section *** (СчетФактура.Контрагент Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СчетФактура.Контрагент Set start)

                // *** End programmer edit section *** (СчетФактура.Контрагент Set start)
                this.fКонтрагент = value;
                // *** Start programmer edit section *** (СчетФактура.Контрагент Set end)

                // *** End programmer edit section *** (СчетФактура.Контрагент Set end)
            }
        }
        
        /// <summary>
        /// Счет фактура.
        /// </summary>
        // *** Start programmer edit section *** (СчетФактура.Склад CustomAttributes)

        // *** End programmer edit section *** (СчетФактура.Склад CustomAttributes)
        [PropertyStorage(new string[] {
                "Склад"})]
        [NotNull()]
        public virtual IIS.Russkaya_zernovachya_kompaniya.Склад Склад
        {
            get
            {
                // *** Start programmer edit section *** (СчетФактура.Склад Get start)

                // *** End programmer edit section *** (СчетФактура.Склад Get start)
                IIS.Russkaya_zernovachya_kompaniya.Склад result = this.fСклад;
                // *** Start programmer edit section *** (СчетФактура.Склад Get end)

                // *** End programmer edit section *** (СчетФактура.Склад Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СчетФактура.Склад Set start)

                // *** End programmer edit section *** (СчетФактура.Склад Set start)
                this.fСклад = value;
                // *** Start programmer edit section *** (СчетФактура.Склад Set end)

                // *** End programmer edit section *** (СчетФактура.Склад Set end)
            }
        }
        
        /// <summary>
        /// Счет фактура.
        /// </summary>
        // *** Start programmer edit section *** (СчетФактура.Сотрудник CustomAttributes)

        // *** End programmer edit section *** (СчетФактура.Сотрудник CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудник"})]
        [NotNull()]
        public virtual IIS.Russkaya_zernovachya_kompaniya.Сотрудник Сотрудник
        {
            get
            {
                // *** Start programmer edit section *** (СчетФактура.Сотрудник Get start)

                // *** End programmer edit section *** (СчетФактура.Сотрудник Get start)
                IIS.Russkaya_zernovachya_kompaniya.Сотрудник result = this.fСотрудник;
                // *** Start programmer edit section *** (СчетФактура.Сотрудник Get end)

                // *** End programmer edit section *** (СчетФактура.Сотрудник Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СчетФактура.Сотрудник Set start)

                // *** End programmer edit section *** (СчетФактура.Сотрудник Set start)
                this.fСотрудник = value;
                // *** Start programmer edit section *** (СчетФактура.Сотрудник Set end)

                // *** End programmer edit section *** (СчетФактура.Сотрудник Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СчетФактураE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СчетФактураE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СчетФактураE", typeof(IIS.Russkaya_zernovachya_kompaniya.СчетФактура));
                }
            }
            
            /// <summary>
            /// "СчетФактураL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СчетФактураL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СчетФактураL", typeof(IIS.Russkaya_zernovachya_kompaniya.СчетФактура));
                }
            }
        }
    }
}
