//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Russkaya_zernovachya_kompaniya
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Тип накладной.
    /// </summary>
    // *** Start programmer edit section *** (ТипНакладной CustomAttributes)

    // *** End programmer edit section *** (ТипНакладной CustomAttributes)
    public enum ТипНакладной
    {
        
        // *** Start programmer edit section *** (ТипНакладной.Расходная CustomAttributes)

        // *** End programmer edit section *** (ТипНакладной.Расходная CustomAttributes)
        Расходная,
        
        // *** Start programmer edit section *** (ТипНакладной.Приходная CustomAttributes)

        // *** End programmer edit section *** (ТипНакладной.Приходная CustomAttributes)
        Приходная,
    }
}
