//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Russkaya_zernovachya_kompaniya
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Тип контрагента.
    /// </summary>
    // *** Start programmer edit section *** (ТипКонтрагента CustomAttributes)

    // *** End programmer edit section *** (ТипКонтрагента CustomAttributes)
    public enum ТипКонтрагента
    {
        
        // *** Start programmer edit section *** (ТипКонтрагента.Поставщик CustomAttributes)

        // *** End programmer edit section *** (ТипКонтрагента.Поставщик CustomAttributes)
        Поставщик,
        
        // *** Start programmer edit section *** (ТипКонтрагента.Клиент CustomAttributes)

        // *** End programmer edit section *** (ТипКонтрагента.Клиент CustomAttributes)
        Клиент,
    }
}
