//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Russkaya_zernovachya_kompaniya
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Товар.
    /// </summary>
    // *** Start programmer edit section *** (Товар CustomAttributes)

    // *** End programmer edit section *** (Товар CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТоварE", new string[] {
            "Описание as \'Описание\'",
            "ЕдИзм as \'Ед изм\'",
            "Название as \'Название\'",
            "КодТовара as \'Код товара\'",
            "ТЧСчФактуры as \'Т ч сч фактуры\'",
            "ТЧСчФактуры.Количество as \'Количество\'",
            "ЗаписьВНакл as \'Запись в накл\'",
            "ЗаписьВНакл.Цена as \'Цена\'",
            "КатегорияТовара as \'Категория товара\'",
            "КатегорияТовара.КодКатегории as \'Код категории\'"}, Hidden=new string[] {
            "ТЧСчФактуры.Количество",
            "ЗаписьВНакл.Цена",
            "КатегорияТовара.КодКатегории"})]
    [MasterViewDefineAttribute("ТоварE", "ТЧСчФактуры", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Количество")]
    [MasterViewDefineAttribute("ТоварE", "ЗаписьВНакл", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Цена")]
    [MasterViewDefineAttribute("ТоварE", "КатегорияТовара", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "КодКатегории")]
    [View("ТоварL", new string[] {
            "Описание as \'Описание\'",
            "ЕдИзм as \'Ед изм\'",
            "Название as \'Название\'",
            "КодТовара as \'Код товара\'",
            "ТЧСчФактуры.Количество as \'Количество\'",
            "ЗаписьВНакл.Цена as \'Цена\'",
            "КатегорияТовара.КодКатегории as \'Код категории\'"})]
    public class Товар : ICSSoft.STORMNET.DataObject
    {
        
        private string fОписание;
        
        private string fЕдИзм;
        
        private string fНазвание;
        
        private string fКодТовара;
        
        private IIS.Russkaya_zernovachya_kompaniya.ТЧСчФактуры fТЧСчФактуры;
        
        private IIS.Russkaya_zernovachya_kompaniya.ЗаписьВНакл fЗаписьВНакл;
        
        private IIS.Russkaya_zernovachya_kompaniya.КатегорияТовара fКатегорияТовара;
        
        // *** Start programmer edit section *** (Товар CustomMembers)

        // *** End programmer edit section *** (Товар CustomMembers)

        
        /// <summary>
        /// ЕдИзм.
        /// </summary>
        // *** Start programmer edit section *** (Товар.ЕдИзм CustomAttributes)

        // *** End programmer edit section *** (Товар.ЕдИзм CustomAttributes)
        [StrLen(255)]
        public virtual string ЕдИзм
        {
            get
            {
                // *** Start programmer edit section *** (Товар.ЕдИзм Get start)

                // *** End programmer edit section *** (Товар.ЕдИзм Get start)
                string result = this.fЕдИзм;
                // *** Start programmer edit section *** (Товар.ЕдИзм Get end)

                // *** End programmer edit section *** (Товар.ЕдИзм Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Товар.ЕдИзм Set start)

                // *** End programmer edit section *** (Товар.ЕдИзм Set start)
                this.fЕдИзм = value;
                // *** Start programmer edit section *** (Товар.ЕдИзм Set end)

                // *** End programmer edit section *** (Товар.ЕдИзм Set end)
            }
        }
        
        /// <summary>
        /// КодТовара.
        /// </summary>
        // *** Start programmer edit section *** (Товар.КодТовара CustomAttributes)

        // *** End programmer edit section *** (Товар.КодТовара CustomAttributes)
        [StrLen(255)]
        public virtual string КодТовара
        {
            get
            {
                // *** Start programmer edit section *** (Товар.КодТовара Get start)

                // *** End programmer edit section *** (Товар.КодТовара Get start)
                string result = this.fКодТовара;
                // *** Start programmer edit section *** (Товар.КодТовара Get end)

                // *** End programmer edit section *** (Товар.КодТовара Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Товар.КодТовара Set start)

                // *** End programmer edit section *** (Товар.КодТовара Set start)
                this.fКодТовара = value;
                // *** Start programmer edit section *** (Товар.КодТовара Set end)

                // *** End programmer edit section *** (Товар.КодТовара Set end)
            }
        }
        
        /// <summary>
        /// Название.
        /// </summary>
        // *** Start programmer edit section *** (Товар.Название CustomAttributes)

        // *** End programmer edit section *** (Товар.Название CustomAttributes)
        [StrLen(255)]
        public virtual string Название
        {
            get
            {
                // *** Start programmer edit section *** (Товар.Название Get start)

                // *** End programmer edit section *** (Товар.Название Get start)
                string result = this.fНазвание;
                // *** Start programmer edit section *** (Товар.Название Get end)

                // *** End programmer edit section *** (Товар.Название Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Товар.Название Set start)

                // *** End programmer edit section *** (Товар.Название Set start)
                this.fНазвание = value;
                // *** Start programmer edit section *** (Товар.Название Set end)

                // *** End programmer edit section *** (Товар.Название Set end)
            }
        }
        
        /// <summary>
        /// Описание.
        /// </summary>
        // *** Start programmer edit section *** (Товар.Описание CustomAttributes)

        // *** End programmer edit section *** (Товар.Описание CustomAttributes)
        [StrLen(255)]
        public virtual string Описание
        {
            get
            {
                // *** Start programmer edit section *** (Товар.Описание Get start)

                // *** End programmer edit section *** (Товар.Описание Get start)
                string result = this.fОписание;
                // *** Start programmer edit section *** (Товар.Описание Get end)

                // *** End programmer edit section *** (Товар.Описание Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Товар.Описание Set start)

                // *** End programmer edit section *** (Товар.Описание Set start)
                this.fОписание = value;
                // *** Start programmer edit section *** (Товар.Описание Set end)

                // *** End programmer edit section *** (Товар.Описание Set end)
            }
        }
        
        /// <summary>
        /// Товар.
        /// </summary>
        // *** Start programmer edit section *** (Товар.ЗаписьВНакл CustomAttributes)

        // *** End programmer edit section *** (Товар.ЗаписьВНакл CustomAttributes)
        [PropertyStorage(new string[] {
                "ЗаписьВНакл"})]
        [NotNull()]
        public virtual IIS.Russkaya_zernovachya_kompaniya.ЗаписьВНакл ЗаписьВНакл
        {
            get
            {
                // *** Start programmer edit section *** (Товар.ЗаписьВНакл Get start)

                // *** End programmer edit section *** (Товар.ЗаписьВНакл Get start)
                IIS.Russkaya_zernovachya_kompaniya.ЗаписьВНакл result = this.fЗаписьВНакл;
                // *** Start programmer edit section *** (Товар.ЗаписьВНакл Get end)

                // *** End programmer edit section *** (Товар.ЗаписьВНакл Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Товар.ЗаписьВНакл Set start)

                // *** End programmer edit section *** (Товар.ЗаписьВНакл Set start)
                this.fЗаписьВНакл = value;
                // *** Start programmer edit section *** (Товар.ЗаписьВНакл Set end)

                // *** End programmer edit section *** (Товар.ЗаписьВНакл Set end)
            }
        }
        
        /// <summary>
        /// Товар.
        /// </summary>
        // *** Start programmer edit section *** (Товар.КатегорияТовара CustomAttributes)

        // *** End programmer edit section *** (Товар.КатегорияТовара CustomAttributes)
        [PropertyStorage(new string[] {
                "КатегорияТовара"})]
        [NotNull()]
        public virtual IIS.Russkaya_zernovachya_kompaniya.КатегорияТовара КатегорияТовара
        {
            get
            {
                // *** Start programmer edit section *** (Товар.КатегорияТовара Get start)

                // *** End programmer edit section *** (Товар.КатегорияТовара Get start)
                IIS.Russkaya_zernovachya_kompaniya.КатегорияТовара result = this.fКатегорияТовара;
                // *** Start programmer edit section *** (Товар.КатегорияТовара Get end)

                // *** End programmer edit section *** (Товар.КатегорияТовара Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Товар.КатегорияТовара Set start)

                // *** End programmer edit section *** (Товар.КатегорияТовара Set start)
                this.fКатегорияТовара = value;
                // *** Start programmer edit section *** (Товар.КатегорияТовара Set end)

                // *** End programmer edit section *** (Товар.КатегорияТовара Set end)
            }
        }
        
        /// <summary>
        /// Товар.
        /// </summary>
        // *** Start programmer edit section *** (Товар.ТЧСчФактуры CustomAttributes)

        // *** End programmer edit section *** (Товар.ТЧСчФактуры CustomAttributes)
        [PropertyStorage(new string[] {
                "ТЧСчФактуры"})]
        [NotNull()]
        public virtual IIS.Russkaya_zernovachya_kompaniya.ТЧСчФактуры ТЧСчФактуры
        {
            get
            {
                // *** Start programmer edit section *** (Товар.ТЧСчФактуры Get start)

                // *** End programmer edit section *** (Товар.ТЧСчФактуры Get start)
                IIS.Russkaya_zernovachya_kompaniya.ТЧСчФактуры result = this.fТЧСчФактуры;
                // *** Start programmer edit section *** (Товар.ТЧСчФактуры Get end)

                // *** End programmer edit section *** (Товар.ТЧСчФактуры Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Товар.ТЧСчФактуры Set start)

                // *** End programmer edit section *** (Товар.ТЧСчФактуры Set start)
                this.fТЧСчФактуры = value;
                // *** Start programmer edit section *** (Товар.ТЧСчФактуры Set end)

                // *** End programmer edit section *** (Товар.ТЧСчФактуры Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТоварE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТоварE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТоварE", typeof(IIS.Russkaya_zernovachya_kompaniya.Товар));
                }
            }
            
            /// <summary>
            /// "ТоварL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТоварL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТоварL", typeof(IIS.Russkaya_zernovachya_kompaniya.Товар));
                }
            }
        }
    }
}
