//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Russkaya_zernovachya_kompaniya
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Т ч сч фактуры.
    /// </summary>
    // *** Start programmer edit section *** (ТЧСчФактуры CustomAttributes)

    // *** End programmer edit section *** (ТЧСчФактуры CustomAttributes)
    [AutoAltered()]
    [Caption("Т ч сч фактуры")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТЧСчФактурыE", new string[] {
            "Количество as \'Количество\'",
            "Сумма as \'Сумма\'"})]
    [View("ТЧСчФактурыL", new string[] {
            "Количество as \'Количество\'",
            "Сумма as \'Сумма\'"})]
    public class ТЧСчФактуры : ICSSoft.STORMNET.DataObject
    {
        
        private int fКоличество;
        
        private double fСумма;
        
        // *** Start programmer edit section *** (ТЧСчФактуры CustomMembers)

        // *** End programmer edit section *** (ТЧСчФактуры CustomMembers)

        
        /// <summary>
        /// Количество.
        /// </summary>
        // *** Start programmer edit section *** (ТЧСчФактуры.Количество CustomAttributes)

        // *** End programmer edit section *** (ТЧСчФактуры.Количество CustomAttributes)
        public virtual int Количество
        {
            get
            {
                // *** Start programmer edit section *** (ТЧСчФактуры.Количество Get start)

                // *** End programmer edit section *** (ТЧСчФактуры.Количество Get start)
                int result = this.fКоличество;
                // *** Start programmer edit section *** (ТЧСчФактуры.Количество Get end)

                // *** End programmer edit section *** (ТЧСчФактуры.Количество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧСчФактуры.Количество Set start)

                // *** End programmer edit section *** (ТЧСчФактуры.Количество Set start)
                this.fКоличество = value;
                // *** Start programmer edit section *** (ТЧСчФактуры.Количество Set end)

                // *** End programmer edit section *** (ТЧСчФактуры.Количество Set end)
            }
        }
        
        /// <summary>
        /// Сумма.
        /// </summary>
        // *** Start programmer edit section *** (ТЧСчФактуры.Сумма CustomAttributes)

        // *** End programmer edit section *** (ТЧСчФактуры.Сумма CustomAttributes)
        public virtual double Сумма
        {
            get
            {
                // *** Start programmer edit section *** (ТЧСчФактуры.Сумма Get start)

                // *** End programmer edit section *** (ТЧСчФактуры.Сумма Get start)
                double result = this.fСумма;
                // *** Start programmer edit section *** (ТЧСчФактуры.Сумма Get end)

                // *** End programmer edit section *** (ТЧСчФактуры.Сумма Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧСчФактуры.Сумма Set start)

                // *** End programmer edit section *** (ТЧСчФактуры.Сумма Set start)
                this.fСумма = value;
                // *** Start programmer edit section *** (ТЧСчФактуры.Сумма Set end)

                // *** End programmer edit section *** (ТЧСчФактуры.Сумма Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТЧСчФактурыE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТЧСчФактурыE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТЧСчФактурыE", typeof(IIS.Russkaya_zernovachya_kompaniya.ТЧСчФактуры));
                }
            }
            
            /// <summary>
            /// "ТЧСчФактурыL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТЧСчФактурыL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТЧСчФактурыL", typeof(IIS.Russkaya_zernovachya_kompaniya.ТЧСчФактуры));
                }
            }
        }
    }
}
