//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Russkaya_zernovachya_kompaniya
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Цена товара.
    /// </summary>
    // *** Start programmer edit section *** (ЦенаТовара CustomAttributes)

    // *** End programmer edit section *** (ЦенаТовара CustomAttributes)
    [AutoAltered()]
    [Caption("Цена товара")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЦенаТовараE", new string[] {
            "Цена as \'Цена\'",
            "ДатаНачала as \'Дата начала\'",
            "ДатаОконч as \'Дата оконч\'",
            "Товар as \'Товар\'",
            "Товар.Описание as \'Описание\'",
            "ТЧСчФактуры as \'Т ч сч фактуры\'",
            "ТЧСчФактуры.Количество as \'Количество\'"}, Hidden=new string[] {
            "Товар.Описание",
            "ТЧСчФактуры.Количество"})]
    [MasterViewDefineAttribute("ЦенаТовараE", "Товар", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Описание")]
    [MasterViewDefineAttribute("ЦенаТовараE", "ТЧСчФактуры", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Количество")]
    [View("ЦенаТовараL", new string[] {
            "Цена as \'Цена\'",
            "ДатаНачала as \'Дата начала\'",
            "ДатаОконч as \'Дата оконч\'",
            "Товар.Описание as \'Описание\'",
            "ТЧСчФактуры.Количество as \'Количество\'"})]
    public class ЦенаТовара : ICSSoft.STORMNET.DataObject
    {
        
        private int fЦена;
        
        private System.DateTime fДатаНачала;
        
        private System.DateTime fДатаОконч;
        
        private IIS.Russkaya_zernovachya_kompaniya.Товар fТовар;
        
        private IIS.Russkaya_zernovachya_kompaniya.ТЧСчФактуры fТЧСчФактуры;
        
        // *** Start programmer edit section *** (ЦенаТовара CustomMembers)

        // *** End programmer edit section *** (ЦенаТовара CustomMembers)

        
        /// <summary>
        /// ДатаНачала.
        /// </summary>
        // *** Start programmer edit section *** (ЦенаТовара.ДатаНачала CustomAttributes)

        // *** End programmer edit section *** (ЦенаТовара.ДатаНачала CustomAttributes)
        public virtual System.DateTime ДатаНачала
        {
            get
            {
                // *** Start programmer edit section *** (ЦенаТовара.ДатаНачала Get start)

                // *** End programmer edit section *** (ЦенаТовара.ДатаНачала Get start)
                System.DateTime result = this.fДатаНачала;
                // *** Start programmer edit section *** (ЦенаТовара.ДатаНачала Get end)

                // *** End programmer edit section *** (ЦенаТовара.ДатаНачала Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЦенаТовара.ДатаНачала Set start)

                // *** End programmer edit section *** (ЦенаТовара.ДатаНачала Set start)
                this.fДатаНачала = value;
                // *** Start programmer edit section *** (ЦенаТовара.ДатаНачала Set end)

                // *** End programmer edit section *** (ЦенаТовара.ДатаНачала Set end)
            }
        }
        
        /// <summary>
        /// ДатаОконч.
        /// </summary>
        // *** Start programmer edit section *** (ЦенаТовара.ДатаОконч CustomAttributes)

        // *** End programmer edit section *** (ЦенаТовара.ДатаОконч CustomAttributes)
        public virtual System.DateTime ДатаОконч
        {
            get
            {
                // *** Start programmer edit section *** (ЦенаТовара.ДатаОконч Get start)

                // *** End programmer edit section *** (ЦенаТовара.ДатаОконч Get start)
                System.DateTime result = this.fДатаОконч;
                // *** Start programmer edit section *** (ЦенаТовара.ДатаОконч Get end)

                // *** End programmer edit section *** (ЦенаТовара.ДатаОконч Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЦенаТовара.ДатаОконч Set start)

                // *** End programmer edit section *** (ЦенаТовара.ДатаОконч Set start)
                this.fДатаОконч = value;
                // *** Start programmer edit section *** (ЦенаТовара.ДатаОконч Set end)

                // *** End programmer edit section *** (ЦенаТовара.ДатаОконч Set end)
            }
        }
        
        /// <summary>
        /// Цена.
        /// </summary>
        // *** Start programmer edit section *** (ЦенаТовара.Цена CustomAttributes)

        // *** End programmer edit section *** (ЦенаТовара.Цена CustomAttributes)
        public virtual int Цена
        {
            get
            {
                // *** Start programmer edit section *** (ЦенаТовара.Цена Get start)

                // *** End programmer edit section *** (ЦенаТовара.Цена Get start)
                int result = this.fЦена;
                // *** Start programmer edit section *** (ЦенаТовара.Цена Get end)

                // *** End programmer edit section *** (ЦенаТовара.Цена Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЦенаТовара.Цена Set start)

                // *** End programmer edit section *** (ЦенаТовара.Цена Set start)
                this.fЦена = value;
                // *** Start programmer edit section *** (ЦенаТовара.Цена Set end)

                // *** End programmer edit section *** (ЦенаТовара.Цена Set end)
            }
        }
        
        /// <summary>
        /// Цена товара.
        /// </summary>
        // *** Start programmer edit section *** (ЦенаТовара.Товар CustomAttributes)

        // *** End programmer edit section *** (ЦенаТовара.Товар CustomAttributes)
        [PropertyStorage(new string[] {
                "Товар"})]
        [NotNull()]
        public virtual IIS.Russkaya_zernovachya_kompaniya.Товар Товар
        {
            get
            {
                // *** Start programmer edit section *** (ЦенаТовара.Товар Get start)

                // *** End programmer edit section *** (ЦенаТовара.Товар Get start)
                IIS.Russkaya_zernovachya_kompaniya.Товар result = this.fТовар;
                // *** Start programmer edit section *** (ЦенаТовара.Товар Get end)

                // *** End programmer edit section *** (ЦенаТовара.Товар Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЦенаТовара.Товар Set start)

                // *** End programmer edit section *** (ЦенаТовара.Товар Set start)
                this.fТовар = value;
                // *** Start programmer edit section *** (ЦенаТовара.Товар Set end)

                // *** End programmer edit section *** (ЦенаТовара.Товар Set end)
            }
        }
        
        /// <summary>
        /// Цена товара.
        /// </summary>
        // *** Start programmer edit section *** (ЦенаТовара.ТЧСчФактуры CustomAttributes)

        // *** End programmer edit section *** (ЦенаТовара.ТЧСчФактуры CustomAttributes)
        [PropertyStorage(new string[] {
                "ТЧСчФактуры"})]
        [NotNull()]
        public virtual IIS.Russkaya_zernovachya_kompaniya.ТЧСчФактуры ТЧСчФактуры
        {
            get
            {
                // *** Start programmer edit section *** (ЦенаТовара.ТЧСчФактуры Get start)

                // *** End programmer edit section *** (ЦенаТовара.ТЧСчФактуры Get start)
                IIS.Russkaya_zernovachya_kompaniya.ТЧСчФактуры result = this.fТЧСчФактуры;
                // *** Start programmer edit section *** (ЦенаТовара.ТЧСчФактуры Get end)

                // *** End programmer edit section *** (ЦенаТовара.ТЧСчФактуры Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЦенаТовара.ТЧСчФактуры Set start)

                // *** End programmer edit section *** (ЦенаТовара.ТЧСчФактуры Set start)
                this.fТЧСчФактуры = value;
                // *** Start programmer edit section *** (ЦенаТовара.ТЧСчФактуры Set end)

                // *** End programmer edit section *** (ЦенаТовара.ТЧСчФактуры Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЦенаТовараE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЦенаТовараE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЦенаТовараE", typeof(IIS.Russkaya_zernovachya_kompaniya.ЦенаТовара));
                }
            }
            
            /// <summary>
            /// "ЦенаТовараL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЦенаТовараL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЦенаТовараL", typeof(IIS.Russkaya_zernovachya_kompaniya.ЦенаТовара));
                }
            }
        }
    }
}
